### ISSUE TITLE
Example code doesn't work, and i get an error while trying to backup

### ISSUE THREAD

**Issue by WebWire-NL** [nokibsarkar/sqlite3-incremental-backup#1]
Hi,
After finally getting the package to work(created a package.json and includdes full path to mjs in import) :) i got the following error :( database is around 30GB :)

---> Restoration started from <---  snapshot1.txt
(node:48038) UnhandledPromiseRejectionWarning: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (30906707968) is greater than possible Buffer: 2147483647 bytes
    at tryCreateBuffer (fs.js:339:13)
    at readFileSync (fs.js:375:14)
    at backup (file:///home/user/node_modules/sqlite3-incremental-backup/sqlite3-incremental-backup.mjs:28:21)
    at file:///home/user/sync.js:6:1
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(node:48038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:48038) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'snapshot1.txt'
    at Object.openSync (fs.js:462:3)
    at readFileSync (fs.js:364:35)
    at restore (file:///home/user/node_modules/sqlite3-incremental-backup/sqlite3-incremental-backup.mjs:66:19)
    at file:///home/user/sync.js:7:1
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(node:48038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by nokibsarkar** [comment]
@WebWire-NL Can you please apply the latest patch (https://github.com/nokibsarkar/sqlite3-incremental-backup/commit/5c3090d36817a51616c812f491331e9f3ef0dfe5) and try again? Actually, my machine is not fast enough to complete the test within a reasonable time. Therefore please test the result yourself and let me know if it fixes. If I get positive feedback, I would publish the patch to npm as well. Currently, the patch is not applied on npm.

**Comment by nokibsarkar** [comment]
@WebWire-NL as for noting, the error is because of nodejs internal error, not any problem with the library itself. It was due to the large buffer size of about 30GB. I did not test with the large buffer.

**Comment by WebWire-NL** [comment]
I'm sorry but it feels all to unstable to test, it seems a good solution for incremental backups but it doesn't feel robust, like the filename for the snapshot is snapshot1.txt with a comment that it should be changed every time.... i think there should be a random filename or incremental filename and the restore function should restore the incrementals by order or something. I don't understand your code exactly so maybe ill digg in or try another solution. I didn't figure out yet. As I'm more into python maybe i'll try the python version. I have a database with a lot of changes which i want to sync to a remote side, it feels like i will end up with a lot of files with this approach. I think i was looking for the wrong solution for my issue, i wanted to sync a database to the other and.... and this option might function very well for incremental backups. Hope i'll ever use it when my database gets bigger! Good luck!

**Comment by nokibsarkar** [comment]
@WebWire-NL  Okay, thanks for your support. Actually, these were meant to work with scripts i.e cronjob/background_process which would run the backup periodically (So, I make the snapshot option should be on your choice may be timestamp-based or incremental based). And I think you did not grab the concept of database incremental backup. Each snapshot file (not the objects file) is independent of each other. I mean if you delete all the snapshots but a single one, you can restore the whole database. Yes, it may seem like a lot of files in a lot of folders because it is splitting your database into chunks and backing up all of them. After any modification to the database, the backing up process will backup the chunk only which was actually modified, thus saving a lot of storage. I think my current implementations only work with local files (Because all the object files must be present during restoration). I implemented timestamp-based naming on snapshot name during backup but you must provide the snapshot name to be restored. Whenever you need your database to go on a specific (past) state, provide that snapshot name on the restore function. Check for the latest commit.


Note: As per your requirements, you need to sync your database to the remote. Then I think the following workflow would do the case:
1. back up your database with a constant snapshot name (maybe `snapshot.txt`), which will overwrite the previous each time you run the backup. (on source machine)
2. Collect all the object files and the snapshot file from the source machine to your target machine (It could be done by my library, but I do not want the library to have dependencies other than standard ones, but I may give a shot if I get chance)
3. restore the current state by providing the snapshot file name you have given in step 1 (on target machine)
I think it may give you a rough idea of how the implementation may work. Hope you all the best.
